chore: Upgrade arti_client to 0.24
umgefahren/libp2p-tor pull request #18
Opened 2024-11-18 00:21 UTC by binarybaron

2024-11-18 08:31 UTC, umgefahren commented
Thanks for your effort. However it looks like it no longer compiles with the version update. This likely to updates or movements. Could you resolve these problems?

2024-11-18 12:27 UTC, binarybaron commented
> Thanks for your effort. However it looks like it no longer compiles with the version update. This likely to updates or movements. Could you resolve these problems?

We are using this for our implementation of [Monero <> Bitcoin atomic swaps](https://github.com/UnstoppableSwap/core). 

I'm super hyped to use this crate, both for privacy and to allow users to listen on an onion address without having to expose any ports. Previously, we bundled a pre-compiled `tor` binary and routed libp2p over the socks5 proxy (and connected to the [control port](https://github.com/torproject/torspec/blob/main/control-spec.txt) to manually create a hidden service) but using this'd be so much simpler! I only recently discovered arti and I love it!

I'm still trying to adapt the code to use the new `arti_client` API. Feel free to jump in and push to this branch if you want to. I haven't worked a lot with runtime agnostic before.

2024-11-18 13:10 UTC, umgefahren commented
I don't know your use case that well but I want to note, that the security could be easily compromised by an incorrect use of identify, so bear that in mind.
Second note that Tor anonymity can be compromised: https://github.com/Attacks-on-Tor/Attacks-on-Tor/blob/master/Thirteen%20years%20of%20Tor%20Attacks.pdf
There are more secure alternatives out there, if you are interested: @hoprnet

2024-11-19 19:40 UTC, umgefahren requested changes
I don't understand some of your questions. Especially the ones you did in [Cargo.toml]. Could you clarify them?

2024-11-19 19:40 UTC, umgefahren commented on Cargo.toml
> +version = "0.2.0"
```suggestion
version = "0.4.0"
```
I think we should go forwards in the version.

2024-11-19 19:40 UTC, umgefahren commented on Cargo.toml
> -authors = ["umgefahren <hannes@umgefahren.xyz>"]
Why would you remove my authorship?

2024-11-19 19:40 UTC, umgefahren commented on Cargo.toml
> +repository = "https://github.com/hannes-furmans/libp2p-community-tor"
This is not the url of this repository.

2024-11-19 19:40 UTC, umgefahren commented on Cargo.toml
> -resolver = "2"
Why would you go back on the modern resolver?

2024-11-19 19:40 UTC, umgefahren commented on Cargo.toml
> -required-features = ["async-std", "rustls"]
Why would you remove the example?

2024-11-19 19:40 UTC, umgefahren commented on Cargo.toml
> -rustc-args = ["--cfg", "docsrs"]
Good catch!

2024-11-19 19:40 UTC, umgefahren commented on src/lib.rs
> -//! ```
Why do you remove the example?

2024-11-19 20:06 UTC, umgefahren commented
oh okay, no worries :)
I just reviewed it because you marked it _ready to review_

2024-11-19 20:09 UTC, binarybaron commented
> oh okay, no worries :) I just reviewed it because you marked it _ready to review_

I know, my fault.

2024-11-20 09:00 UTC, binarybaron commented
@umgefahren This is ready for review.

2024-11-20 09:50 UTC, umgefahren approved these changes
Just the little thing about the entry point. Otherwise: Thank you!

2024-11-20 09:50 UTC, umgefahren commented on src/lib.rs
> -//! Main entrypoint of the crate: [`TorTransport`]
I still think that's helpful :)

2024-11-20 09:56 UTC, merged

2024-11-20 10:00 UTC, umgefahren commented
Thank you for your work! May I ask why you didn't update to libp2p to 0.54.1?

2024-11-20 10:31 UTC, binarybaron commented
> Thank you for your work! May I ask why you didn't update to libp2p to 0.54.1?

We are still on 0.53. Once we upgrade, I'll open a PR to upgrade this crate too.